//! HLL Sketch Serialization Compatibility Tests
//!
//! These tests verify binary compatibility with Apache DataSketches implementations:
//! - Java (datasketches-java)
//! - C++ (datasketches-cpp)
//! - Go (datasketches-go)
//!
//! Test data is generated by the reference implementations and stored in:
//! `tests/datasketches-go/serialization_test_data/`

use std::fs;
use std::path::PathBuf;

use datasketches_rust::hll::sketch::HllSketch;

const TEST_DATA_DIR: &str = "tests/datasketches-go/serialization_test_data";

fn get_test_data_path(sub_dir: &str, name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join(TEST_DATA_DIR)
        .join(sub_dir)
        .join(name)
}

fn test_sketch_file(path: PathBuf, expected_cardinality: usize, expected_lg_k: u8) {
    let bytes = fs::read(&path).expect("file should exist and should be readable");
    let sketch1 = HllSketch::deserialize(&bytes).expect("deserialization should succeed");

    assert_eq!(
        sketch1.lg_config_k(),
        expected_lg_k,
        "Wrong lg_config_k in {}",
        path.display()
    );

    // TODO: implement check with 2% error rate
    _ = expected_cardinality;

    // Serialize and deserialize again to test round-trip
    let serialized_bytes = sketch1.serialize().expect("serialization should succeed");
    let sketch2 = HllSketch::deserialize(&serialized_bytes)
        .expect("round-trip deserialization should succeed");

    // Check that both sketches are functionally equivalent
    assert_eq!(
        sketch2.lg_config_k(),
        sketch1.lg_config_k(),
        "lg_config_k mismatch after round-trip for {}",
        path.display()
    );

    // Check that the sketches are functionally equal
    assert!(
        sketch1.equals(&sketch2),
        "Sketches are not equal after round-trip for {}",
        path.display()
    );
}

#[test]
fn test_java_hll4_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll4_n{}_java.sk", n);
        let path = get_test_data_path("java_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_java_hll6_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll6_n{}_java.sk", n);
        let path = get_test_data_path("java_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_java_hll8_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll8_n{}_java.sk", n);
        let path = get_test_data_path("java_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_cpp_hll4_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll4_n{}_cpp.sk", n);
        let path = get_test_data_path("cpp_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_cpp_hll6_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll6_n{}_cpp.sk", n);
        let path = get_test_data_path("cpp_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_cpp_hll8_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll8_n{}_cpp.sk", n);
        let path = get_test_data_path("cpp_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_go_hll4_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll4_n{}_go.sk", n);
        let path = get_test_data_path("go_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_go_hll6_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll6_n{}_go.sk", n);
        let path = get_test_data_path("go_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}

#[test]
fn test_go_hll8_compatibility() {
    let test_cases = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];

    for n in test_cases {
        let filename = format!("hll8_n{}_go.sk", n);
        let path = get_test_data_path("go_generated_files", &filename);
        test_sketch_file(path, n, 12);
    }
}
